# Generated by Django 6.0.2 on 2026-02-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('police_commander', 'Police Commander'), ('officer', 'Officer'), ('crime_desk', 'Crime Desk Officer')], default='crime_desk', max_length=20),
        ),
    ]
