# Generated by Django 6.0.2 on 2026-02-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('constable', 'Constable'), ('corporal', 'Corporal'), ('sergeant', 'Sergeant'), ('inspector', 'Inspector'), ('chief_inspector', 'Chief Inspector'), ('commander', 'Commander')], default='constable', max_length=20),
        ),
    ]
