# Generated by Django 6.0.2 on 2026-02-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_remove_profile_role_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('police_commander', 'Police Commander'), ('officer', 'Officer'), ('crime_desk', 'Crime Desk Officer')], default='crime_desk', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True, choices=[('detective', 'Detective'), ('corporal', 'Corporal'), ('sergeant', 'Sergeant'), ('constable', 'Constable')], max_length=20),
        ),
    ]
