# Generated by Django 6.0.2 on 2026-02-20 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_inventoryitem_roster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob_number', models.CharField(blank=True, help_text='Auto-generated OB Number', max_length=50, unique=True)),
                ('incident_datetime', models.DateTimeField(help_text='When did the incident occur?')),
                ('location', models.CharField(help_text='Exact location of the incident', max_length=255)),
                ('incident_type', models.CharField(choices=[('theft', 'Theft / Robbery'), ('assault', 'Assault / Affray'), ('traffic', 'Traffic Accident'), ('fraud', 'Fraud / Forgery'), ('homicide', 'Homicide'), ('missing', 'Missing Person'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(help_text='Detailed narrative of the incident')),
                ('reporter_name', models.CharField(max_length=150)),
                ('reporter_id_number', models.CharField(help_text='National ID or Passport Number', max_length=50)),
                ('reporter_phone', models.CharField(max_length=20)),
                ('persons_involved', models.TextField(blank=True, help_text='Names and details of suspects, victims, or witnesses')),
                ('additional_info', models.TextField(blank=True, help_text='Any extra details, weapon descriptions, vehicle plates, etc.')),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('assigned_officers', models.ManyToManyField(blank=True, help_text='Officers assigned to this case', related_name='investigating_cases', to=settings.AUTH_USER_MODEL)),
                ('desk_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
