# Generated by Django 6.0.2 on 2026-02-21 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='incident_type',
            field=models.CharField(choices=[('theft', 'Theft / Robbery'), ('assault', 'Assault'), ('traffic', 'Traffic Accident'), ('fraud', 'Fraud'), ('homicide', 'Homicide'), ('missing', 'Missing Person'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='ArrestedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(blank=True, help_text='ID or Passport Number', max_length=20, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_arrested', models.DateTimeField(auto_now_add=True)),
                ('offense', models.CharField(help_text='Specific reason for arrest', max_length=200)),
                ('cell_number', models.CharField(blank=True, help_text='Holding cell assignment', max_length=10, null=True)),
                ('status', models.CharField(choices=[('in_custody', 'In Custody'), ('released_bail', 'Released on Bail'), ('transferred', 'Transferred to Prison/Court'), ('released_free', 'Released without Charge')], default='in_custody', max_length=20)),
                ('arresting_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrests_made', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='reporting.case')),
            ],
        ),
    ]
