# Generated by Django 6.0.2 on 2026-02-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_alter_case_incident_type_arrestedperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrestedperson',
            name='related_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspects', to='reporting.case'),
        ),
    ]
