# Generated by Django 6.0.2 on 2026-02-22 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_alter_arrestedperson_related_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text="Short name (e.g., '9mm Handgun' or 'Stolen iPhone')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the item and its condition.')),
                ('status', models.CharField(choices=[('in_locker', 'In Locker'), ('at_lab', 'At Forensics / Lab'), ('in_court', 'Presented in Court'), ('released', 'Released to Owner'), ('destroyed', 'Destroyed')], default='in_locker', max_length=50)),
                ('storage_location', models.CharField(help_text='e.g., Locker A-12, Safe 3', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evidence_photos/')),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('logging_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_evidence', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='reporting.case')),
            ],
        ),
    ]
