# Generated by Django 6.0.2 on 2026-02-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='status',
            field=models.CharField(choices=[('in_locker', 'In Locker'), ('at_lab', 'At the Lab'), ('in_court', 'Presented in Court'), ('released', 'Released to Owner'), ('destroyed', 'Destroyed')], default='in_locker', max_length=50),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='storage_location',
            field=models.CharField(max_length=100),
        ),
    ]
