# Generated by Django 6.0.2 on 2026-03-05 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_alter_evidence_item_name_alter_evidence_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='name',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('weapon', 'Firearm / Weapon'), ('vehicle', 'Police Vehicle'), ('radio', 'Communication / Radio'), ('uniform', 'Uniform / Gear'), ('stationery', 'Office Supplies / Stationery'), ('other', 'Other Equipment')], default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_name',
            field=models.CharField(default='Unknown Item', help_text='e.g., Patrol Car 04, Handcuffs, A4 Paper Reams', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Leave blank for bulk items.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available in Store'), ('assigned', 'Assigned to Officer'), ('maintenance', 'Under Maintenance / Repair'), ('lost_damaged', 'Lost / Damaged')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='logging_officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='logged_evidence', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of items (useful for bulk stationery).'),
        ),
    ]
