# Generated by Django 6.0.2 on 2026-03-05 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_remove_inventoryitem_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('vehicle', 'Police Vehicle'), ('radio', 'Radio'), ('uniform', 'Uniform'), ('gear', 'Gear'), ('stationery', 'Office Supplies / Stationery'), ('other', 'Other Equipment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available in Store'), ('assigned', 'Assigned to Officer'), ('maintenance', 'Under Maintenance'), ('lost_damaged', 'Lost / Damaged')], default='available', max_length=50),
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_time', models.CharField(choices=[('morning', 'Morning Shift (0600 - 1400 hrs)'), ('evening', 'Evening Shift (1400 - 2200 hrs)'), ('night', 'Night Shift (2200 - 0600 hrs)')], max_length=20)),
                ('duty_type', models.CharField(choices=[('patrol', 'General Patrol'), ('report_desk', 'Report Desk'), ('guard', 'Cell Duty'), ('respond', 'Respond to Calls'), ('sguard', 'Station Guard'), ('traffic', 'Traffic Control'), ('investigation', 'Active Investigation'), ('reserve', 'Standby')], max_length=20)),
                ('commander_notes', models.TextField(blank=True, null=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shift_date', 'shift_time'],
                'unique_together': {('officer', 'shift_date', 'shift_time')},
            },
        ),
    ]
